-- =============================================================================
-- FITLIFE GYM MANAGEMENT — UNIFIED SUPABASE SCHEMA
-- =============================================================================
-- Target: Supabase (PostgreSQL 15+)
-- Run the ENTIRE file in the Supabase SQL Editor. It is safe to re-run:
-- it drops and recreates all FitLife objects (FRESH START — wipes data).
--
-- Contents:
--   1. Fresh-start drops
--   2. RBAC           : roles, permissions, role_permissions, users
--   3. Catalog        : branches, plans, plan_features, plan_lockers
--   4. Staff          : trainers, employees, employee_payrolls
--   5. Lockers        : lockers, locker_assignments
--   6. Members        : admission_submissions, members
--   7. Finance        : discounts, invoices, payments, expenses
--   8. Operations     : attendance, sms_settings, sms_campaigns, advertisements
--   9. AI plans       : ai_workout_plans, ai_diet_plans
--  10. Recruitment    : job_postings, job_applications
--  11. Indexes & dashboard view
--  12. Triggers (updated_at, member codes, new-auth-user profile)
--  13. Row Level Security + grants
--  14. Seed data (roles, branches, plans, features)
--
-- Security model:
--   anon         : INSERT admission submissions, READ branches/plans/features
--   authenticated: full access to all tables (admin panel)
--   service_role : bypasses RLS (server-side only, never ship in VITE_ vars)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. FRESH-START DROPS (safe no-ops on an empty database)
-- -----------------------------------------------------------------------------
drop trigger if exists on_auth_user_created on auth.users;

-- Legacy tables from earlier schema revisions (supabase-fix*.sql / old schema.sql)
drop table if exists
  public.diet_plan_meals, public.diet_plans,
  public.member_applications, public.subscription_features, public.subscription_plans,
  public.attendances
cascade;

drop view if exists public.vw_dashboard_metrics;

drop table if exists
  public.job_applications, public.job_postings,
  public.ai_diet_plans, public.ai_workout_plans,
  public.advertisements, public.sms_campaigns, public.sms_settings,
  public.attendance,
  public.expenses, public.payments, public.invoices, public.discounts,
  public.locker_assignments, public.members, public.admission_submissions,
  public.lockers,
  public.employee_payrolls, public.employees, public.trainers,
  public.plan_lockers, public.plan_features, public.plans, public.branches,
  public.users, public.role_permissions, public.permissions, public.roles
cascade;

-- -----------------------------------------------------------------------------
-- 2. EXTENSIONS & HELPERS
-- -----------------------------------------------------------------------------
create extension if not exists pgcrypto;

-- updated_at maintenance (attached in section 12)
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- -----------------------------------------------------------------------------
-- 3. RBAC — ROLES & PERMISSIONS (System Management / Access Control)
-- -----------------------------------------------------------------------------
create table public.roles (
  id                    bigint generated by default as identity primary key,
  name                  text not null unique,          -- 'Super Admin', 'Branch Manager', 'Receptionist', 'Trainer', 'Accountant'
  description           text,
  can_apply_discount    boolean default false,
  max_discount_percentage numeric(5,2) default 0.00,
  can_approve_members   boolean default false,
  can_manage_lockers    boolean default true,
  can_manage_finances   boolean default false,
  created_at            timestamptz default now(),
  updated_at            timestamptz default now()
);

create table public.permissions (
  id          bigint generated by default as identity primary key,
  module      text not null,        -- 'members', 'accounts', 'attendance', 'discounts'...
  action      text not null,        -- 'create', 'read', 'update', 'delete', 'approve'
  description text,
  unique (module, action)
);

create table public.role_permissions (
  role_id       bigint not null references public.roles(id) on delete cascade,
  permission_id bigint not null references public.permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);

-- Staff/system accounts. Login credentials live in Supabase Auth;
-- this table holds profile + role. Linked 1:1 via auth_uid.
create table public.users (
  id          bigint generated by default as identity primary key,
  auth_uid    uuid unique references auth.users(id) on delete cascade,
  role_id     bigint references public.roles(id),
  name        text not null,
  email       text not null unique,
  phone       text,
  avatar      text,
  status      text not null default 'Active' check (status in ('Active','Inactive','Suspended')),
  last_login_at timestamptz,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- 4. CATALOG — BRANCHES, SUBSCRIPTION PLANS
-- -----------------------------------------------------------------------------
-- code is the slug used by the public admission form ('dhanmondi', 'banani'...)
create table public.branches (
  id         bigint generated by default as identity primary key,
  code       text not null unique,
  name       text not null,
  address    text,
  phone      text,
  status     text not null default 'Active' check (status in ('Active','Inactive')),
  created_at timestamptz default now()
);

-- code is the slug used by the public admission form ('basic','standard','premium')
create table public.plans (
  id             bigint generated by default as identity primary key,
  code           text not null unique,
  name           text not null,
  billing_period text not null default 'monthly' check (billing_period in ('monthly','quarterly','yearly')),
  duration_days  int not null default 30,
  base_price     numeric(10,2) not null,
  vat_percentage numeric(5,2) default 5.00,
  is_popular     boolean default false,
  status         text not null default 'Active' check (status in ('Active','Inactive')),
  created_at     timestamptz default now(),
  updated_at     timestamptz default now()
);

create table public.plan_features (
  id            bigint generated by default as identity primary key,
  plan_id       bigint not null references public.plans(id) on delete cascade,
  feature_name  text not null,
  is_included   boolean default true,
  unique (plan_id, feature_name)
);

create table public.plan_lockers (
  id                 bigint generated by default as identity primary key,
  plan_id            bigint not null references public.plans(id) on delete cascade,
  locker_zone        text not null,   -- 'Standard Zone', 'Executive Zone', 'VIP Suite'
  is_complimentary   boolean default false,
  additional_fee     numeric(10,2) default 0.00
);

-- -----------------------------------------------------------------------------
-- 5. STAFF — TRAINERS, EMPLOYEES, PAYROLL
-- -----------------------------------------------------------------------------
create table public.trainers (
  id              bigint generated by default as identity primary key,
  user_id         bigint references public.users(id) on delete set null,
  name            text not null,
  specialty       text not null,      -- 'Strength & Conditioning', 'Cardio & HIIT', 'Yoga', 'CrossFit', 'Nutrition'
  phone           text not null,
  email           text,
  rating          numeric(2,1) default 5.0,
  active_clients  int default 0,
  is_available    boolean default true,
  monthly_salary  numeric(10,2) default 0.00,
  avatar          text,
  created_at      timestamptz default now()
);

create table public.employees (
  id             bigint generated by default as identity primary key,
  user_id        bigint references public.users(id) on delete set null,
  name           text not null,
  employee_code  text unique,          -- auto-style code, nullable for easy inserts
  role           text not null,        -- 'Front Desk Manager', 'Floor Supervisor', 'Accountant'...
  department     text not null,        -- 'Reception', 'Operations', 'Finance', 'Maintenance'
  phone          text not null,
  email          text,
  joined_date    date not null default current_date,
  monthly_salary numeric(10,2) not null default 0,
  status         text not null default 'Active' check (status in ('Active','On Leave','Terminated')),
  avatar         text,
  created_at     timestamptz default now()
);

create table public.employee_payrolls (
  id           bigint generated by default as identity primary key,
  employee_id  bigint not null references public.employees(id) on delete cascade,
  month_year   text not null,          -- '2026-08'
  base_salary  numeric(10,2) not null,
  bonus        numeric(10,2) default 0.00,
  deductions   numeric(10,2) default 0.00,
  net_paid     numeric(10,2) not null,
  payment_date date not null default current_date,
  status       text not null default 'Paid' check (status in ('Paid','Pending')),
  created_at   timestamptz default now(),
  unique (employee_id, month_year)
);

-- -----------------------------------------------------------------------------
-- 6. LOCKERS
-- -----------------------------------------------------------------------------
create table public.lockers (
  id            bigint generated by default as identity primary key,
  locker_number text not null unique,
  zone          text not null,        -- 'Zone A', 'Zone B', 'Zone VIP'
  type          text not null default 'Standard' check (type in ('Standard','Digital','VIP Executive')),
  status        text not null default 'Available' check (status in ('Available','Occupied','Maintenance')),
  monthly_fee   numeric(10,2) default 500.00,
  created_at    timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- 7. MEMBERS — PUBLIC ADMISSION FORM + MEMBER RECORDS
-- -----------------------------------------------------------------------------
-- Public 5-step admission form inserts here as anon.
-- Column set is a contract with admission-form/src/components/AdmissionForm.jsx
-- and src/components/AdmissionForm.jsx — do not rename.
create table public.admission_submissions (
  id                 bigint generated by default as identity primary key,
  branch             text not null,                      -- slug: 'dhanmondi' | 'banani' ...
  plan               text not null,                      -- slug: 'basic' | 'standard' | 'premium'
  first_name         text not null,
  last_name          text not null,
  email              text,
  phone              text not null,
  date_of_birth      date,
  gender             text check (gender is null or gender in ('male','female','other')),  -- lowercase: matches the public form
  address            text,
  blood_group        text,
  height             numeric(5,1),                       -- cm
  weight             numeric(5,1),                       -- kg
  medical_conditions text,
  allergies          text,
  emergency_name     text not null,
  emergency_relation text,
  emergency_phone    text not null,
  status             text not null default 'Pending' check (status in ('Pending','Approved','Rejected')),
  submitted_at       timestamptz not null default now(),
  reviewed_at        timestamptz,
  reviewed_by        bigint references public.users(id)
);

-- Member record. Created by staff approving an admission_submissions row.
-- Column set is a contract with src/pages/Admissions.jsx — do not rename.
create table public.members (
  id              bigint generated by default as identity primary key,
  member_code     text unique,                           -- auto-filled: FLM-000123
  submission_id   bigint unique references public.admission_submissions(id) on delete set null,

  first_name      text not null,
  last_name       text not null,
  email           text,
  phone           text not null,
  gender          text,
  dob             date,
  address         text,
  blood_group     text,
  height          numeric(5,1),
  weight          numeric(5,1),

  -- Display values written by the app ('Basic' / 'Standard' / 'Premium',
  -- branch slug). Kept as text for frontend compatibility; the canonical
  -- records live in plans / branches.
  plan            text not null default 'Basic',
  branch          text,

  trainer_id      bigint references public.trainers(id) on delete set null,
  locker_id       bigint references public.lockers(id) on delete set null,

  status          text not null default 'Active' check (status in ('Active','Inactive','Expiring','Expired')),
  joined          date not null default current_date,
  expiry          date not null,
  visits          int not null default 0,
  emergency_name  text,
  emergency_phone text,

  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

create table public.locker_assignments (
  id             bigint generated by default as identity primary key,
  locker_id      bigint not null references public.lockers(id) on delete cascade,
  member_id      bigint not null references public.members(id) on delete cascade,
  assigned_date  date not null default current_date,
  expiry_date    date not null,
  status         text not null default 'Active' check (status in ('Active','Released')),
  created_at     timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- 8. FINANCE — DISCOUNT ENGINE, INVOICES, PAYMENTS, EXPENSES
-- -----------------------------------------------------------------------------
-- Dynamic Discount Engine:
--   percentage: amount = base * value/100      flat: amount = min(value, base)
create table public.discounts (
  id              bigint generated by default as identity primary key,
  discount_type   text not null check (discount_type in ('percentage','flat')),
  discount_value  numeric(10,2) not null,               -- 15.00 => 15% | 500.00 => 500 BDT
  discount_amount numeric(10,2) not null,               -- computed monetary amount
  reason_note     text,                                 -- 'Seasonal Promo', 'Referral'...
  applied_by      bigint references public.users(id),
  created_at      timestamptz default now()
);

create table public.invoices (
  id              bigint generated by default as identity primary key,
  invoice_number  text not null unique,                 -- 'INV-2026-0042'
  member_id       bigint not null references public.members(id) on delete cascade,
  plan_id         bigint references public.plans(id),
  discount_id     bigint references public.discounts(id) on delete set null,

  base_amount     numeric(10,2) not null,
  discount_amount numeric(10,2) not null default 0,
  tax_amount      numeric(10,2) not null default 0,
  net_payable     numeric(10,2) not null,
  paid_amount     numeric(10,2) not null default 0,
  due_amount      numeric(10,2) not null default 0,
  payment_status  text not null default 'Due' check (payment_status in ('Paid','Partial','Due')),
  payment_method  text default 'CASH' check (payment_method in ('CASH','bKASH','ROCKET','NAGAD','CARD','BANK')),
  invoice_date    date not null default current_date,
  due_date        date,
  notes           text,
  created_at      timestamptz default now()
);

-- Payment receipts. Joined from src/pages/Payments.jsx as
-- members(first_name, last_name) — member_id FK is required for that embed.
create table public.payments (
  id                   bigint generated by default as identity primary key,
  receipt_number       text unique,                     -- 'RCT-000123', nullable
  invoice_id           bigint references public.invoices(id) on delete set null,
  member_id            bigint not null references public.members(id) on delete cascade,
  plan                 text not null,
  amount               numeric(12,2) not null,          -- BDT, numeric (frontend formats with ৳)
  method               text not null default 'CASH' check (method in ('CASH','bKASH','ROCKET','NAGAD','CARD','BANK')),
  status               text not null default 'Paid' check (status in ('Paid','Pending','Partial','Due')),
  transaction_reference text,
  collected_by         bigint references public.users(id),
  payment_date         timestamptz not null default now()
);

create table public.expenses (
  id             bigint generated by default as identity primary key,
  expense_title  text not null,
  category       text not null,      -- 'Equipment Maintenance', 'Utilities', 'Salaries'...
  amount         numeric(10,2) not null,
  payment_method text default 'BANK' check (payment_method in ('CASH','bKASH','ROCKET','NAGAD','CARD','BANK')),
  expense_date   date not null default current_date,
  approved_by    bigint references public.users(id),
  receipt_doc    text,
  notes          text,
  created_at     timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- 9. OPERATIONS — ATTENDANCE, SMS, ADVERTISEMENTS
-- -----------------------------------------------------------------------------
create table public.attendance (
  id              bigint generated by default as identity primary key,
  member_id       bigint not null references public.members(id) on delete cascade,
  attendance_date date not null default current_date,
  check_in_time   time not null default now()::time,
  check_out_time  time,
  status          text not null default 'In' check (status in ('In','Out')),
  method          text not null default 'Manual Admin' check (method in ('RFID Card','Biometric','Manual Admin','Barcode')),
  created_at      timestamptz default now()
);

-- NOTE: api_key is readable by authenticated admin users only (RLS);
-- anon can never read this table.
create table public.sms_settings (
  id                bigint generated by default as identity primary key,
  provider_name     text not null default 'Greenweb Bangladesh',
  api_key           text,
  sender_id         text not null default 'FITLIFE',
  remaining_balance int not null default 0,
  updated_at        timestamptz default now()
);

create table public.sms_campaigns (
  id              bigint generated by default as identity primary key,
  title           text not null,
  recipient_type  text not null,      -- 'All Members', 'Active Only', 'Expiring Members', 'Custom List'
  message         text not null,
  recipient_count int not null default 0,
  cost_credits    int not null default 0,
  status          text not null default 'Sent' check (status in ('Draft','Sent','Scheduled')),
  sent_by         bigint references public.users(id),
  sent_at         timestamptz default now()
);

create table public.advertisements (
  id           bigint generated by default as identity primary key,
  title        text not null,
  banner_url   text not null,
  target_url   text,
  position     text not null default 'Dashboard Header' check (position in ('Dashboard Header','Member Mobile App','Locker TV Display')),
  impressions  int not null default 0,
  clicks       int not null default 0,
  start_date   date not null,
  end_date     date not null,
  status       text not null default 'Active' check (status in ('Active','Scheduled','Expired')),
  created_at   timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- 10. AI WORKOUT & DIET PLANS
-- -----------------------------------------------------------------------------
create table public.ai_workout_plans (
  id                bigint generated by default as identity primary key,
  member_id         bigint not null references public.members(id) on delete cascade,
  plan_title        text not null,
  fitness_goal      text not null,     -- 'Hypertrophy', 'Fat Loss', 'Strength', 'Endurance'
  experience_level  text not null,     -- 'Beginner', 'Intermediate', 'Advanced'
  days_per_week     int not null default 4,
  routine_json      jsonb not null,    -- [{ day, exercises: [{ name, sets, reps, rest }] }]
  ai_generated_notes text,
  created_at        timestamptz default now()
);

create table public.ai_diet_plans (
  id                 bigint generated by default as identity primary key,
  member_id          bigint not null references public.members(id) on delete cascade,
  plan_title         text not null,
  target_goal        text not null,    -- 'Muscle Building', 'Fat Loss Shred', 'Balanced Wellness'
  daily_calories     int not null,
  protein_grams      int not null,
  carbs_grams        int not null,
  fats_grams         int not null,
  meals_json         jsonb not null,   -- [{ time, name, items, calories }]
  dietary_preference text not null default 'Non-Veg' check (dietary_preference in ('Non-Veg','Vegetarian','Vegan','Keto','High Protein')),
  created_at         timestamptz default now()
);

-- -----------------------------------------------------------------------------
-- 11. RECRUITMENT
-- -----------------------------------------------------------------------------
create table public.job_postings (
  id           bigint generated by default as identity primary key,
  job_title    text not null,
  department   text not null,          -- 'Fitness', 'Reception', 'Maintenance', 'Management'
  job_type     text not null default 'Full Time' check (job_type in ('Full Time','Part Time','Contract')),
  salary_range text,
  vacancies    int not null default 1,
  description  text,
  requirements text,
  status       text not null default 'Open' check (status in ('Open','Closed','Draft')),
  posted_date  date not null default current_date
);

create table public.job_applications (
  id               bigint generated by default as identity primary key,
  job_id           bigint not null references public.job_postings(id) on delete cascade,
  candidate_name   text not null,
  candidate_phone  text not null,
  candidate_email  text not null,
  resume_url       text,
  experience_years numeric(3,1),
  status           text not null default 'Applied' check (status in ('Applied','Screened','Interview','Hired','Rejected')),
  applied_at       timestamptz not null default now()
);

-- =============================================================================
-- 12. INDEXES
-- =============================================================================
create index idx_users_role            on public.users(role_id);
create index idx_members_status        on public.members(status);
create index idx_members_phone         on public.members(phone);
create index idx_members_branch        on public.members(branch);
create index idx_members_expiry        on public.members(expiry);
create index idx_members_trainer       on public.members(trainer_id);
create index idx_submissions_status    on public.admission_submissions(status);
create index idx_submissions_submitted on public.admission_submissions(submitted_at);
create index idx_locker_assign_member  on public.locker_assignments(member_id);
create index idx_attendance_date       on public.attendance(attendance_date);
create index idx_attendance_member     on public.attendance(member_id);
create index idx_invoices_date         on public.invoices(invoice_date);
create index idx_invoices_member       on public.invoices(member_id);
create index idx_invoices_status       on public.invoices(payment_status);
create index idx_payments_date         on public.payments(payment_date);
create index idx_payments_member       on public.payments(member_id);
create index idx_expenses_date         on public.expenses(expense_date);
create index idx_lockers_status        on public.lockers(status);
create index idx_payroll_month         on public.employee_payrolls(month_year);
create index idx_job_apps_job          on public.job_applications(job_id);
create index idx_job_apps_status       on public.job_applications(status);

-- =============================================================================
-- 13. DASHBOARD VIEW (14 summary metrics used by src/pages/Dashboard.jsx)
-- =============================================================================
create or replace view public.vw_dashboard_metrics as
select
  (select count(*) from public.members)                                                        as total_members,
  (select count(*) from public.members where status = 'Active')                                as active_members,
  (select count(*) from public.members where status in ('Inactive','Expired'))                 as inactive_members,
  (select count(*) from public.admission_submissions where status = 'Pending')                  as pending_applications,
  (select count(*) from public.plans where status = 'Active')                                  as total_plans,
  (select count(*) from public.employees where status = 'Active')                              as total_employees,
  (select remaining_balance from public.sms_settings limit 1)                                  as remaining_sms,
  (select coalesce(sum(net_payable), 0) from public.invoices
     where date_trunc('month', invoice_date) = date_trunc('month', current_date))              as monthly_sales,
  (select coalesce(sum(net_payable), 0) from public.invoices where invoice_date = current_date) as today_sales_invoice,
  (select coalesce(sum(amount), 0) from public.payments
     where payment_date::date = current_date)                                                  as today_sales_payment,
  (select coalesce(sum(amount), 0) from public.expenses
     where date_trunc('month', expense_date) = date_trunc('month', current_date))              as monthly_expense,
  (select count(*) from public.members
     where date_trunc('month', joined) = date_trunc('month', current_date))                    as monthly_admissions,
  (select count(*) from public.members where expiry = current_date)                            as expiring_today,
  (select count(*) from public.attendance
     where attendance_date = current_date and status = 'In')                                   as present_members_now;

-- =============================================================================
-- 14. TRIGGERS
-- =============================================================================
-- updated_at maintenance
create or replace trigger trg_roles_updated_at
  before update on public.roles
  for each row execute function public.set_updated_at();

create or replace trigger trg_users_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

create or replace trigger trg_plans_updated_at
  before update on public.plans
  for each row execute function public.set_updated_at();

create or replace trigger trg_members_updated_at
  before update on public.members
  for each row execute function public.set_updated_at();

create or replace trigger trg_submissions_updated_at
  before update on public.admission_submissions
  for each row execute function public.set_updated_at();

create or replace trigger trg_sms_settings_updated_at
  before update on public.sms_settings
  for each row execute function public.set_updated_at();

-- Auto member code: FLM-000123 (members.member_code may also be set manually)
create or replace function public.set_member_code()
returns trigger
language plpgsql
as $$
begin
  if new.member_code is null then
    update public.members
       set member_code = 'FLM-' || lpad(new.id::text, 6, '0')
     where id = new.id;
  end if;
  return null;
end;
$$;

create or replace trigger trg_members_code
  after insert on public.members
  for each row execute function public.set_member_code();

-- Auto-create a staff profile row when a Supabase Auth user is created
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (auth_uid, email, name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1))
  )
  on conflict (auth_uid) do nothing;
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =============================================================================
-- 15. ROW LEVEL SECURITY
-- =============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'roles','permissions','role_permissions','users',
    'branches','plans','plan_features','plan_lockers',
    'trainers','employees','employee_payrolls',
    'lockers','locker_assignments',
    'admission_submissions','members',
    'discounts','invoices','payments','expenses',
    'attendance','sms_settings','sms_campaigns','advertisements',
    'ai_workout_plans','ai_diet_plans',
    'job_postings','job_applications'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);

    -- Admin panel (signed-in staff): full access
    execute format(
      'create policy "authenticated all on %I" on public.%I for all to authenticated using (true) with check (true)',
      t, t
    );
  end loop;
end $$;

-- Public admission form (anon): INSERT submissions only
create policy "anon insert admissions"
  on public.admission_submissions
  for insert to anon
  with check (true);

-- Public form catalog reads (anon)
create policy "anon read branches"
  on public.branches for select to anon using (true);
create policy "anon read plans"
  on public.plans for select to anon using (true);
create policy "anon read plan features"
  on public.plan_features for select to anon using (true);

-- =============================================================================
-- 16. GRANTS
-- =============================================================================
grant usage on schema public to anon, authenticated;

grant all on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

grant insert on public.admission_submissions to anon;
grant select on public.branches, public.plans, public.plan_features to anon;
grant usage on all sequences in schema public to anon;   -- identity columns on insert

-- NOTE: if you add new tables later, re-run for them:
--   grant all on all tables in schema public to authenticated;
--   grant usage, select on all sequences in schema public to authenticated;
-- plus an "authenticated all on <table>" policy (see section 15).

-- =============================================================================
-- 17. SEED DATA
-- =============================================================================
insert into public.roles
  (name, description, can_apply_discount, max_discount_percentage, can_approve_members, can_manage_lockers, can_manage_finances)
values
  ('Super Admin',    'Full system access',                         true, 100.00, true, true,  true),
  ('Branch Manager', 'Branch-level management',                    true,  15.00, true, true,  true),
  ('Receptionist',   'Front desk: admissions, check-ins, lockers', false,  0.00, false, true, false),
  ('Trainer',        'Coaching staff',                              false,  0.00, false, false, false),
  ('Accountant',     'Finance & payroll',                           true,   5.00, false, false, true)
on conflict (name) do nothing;

insert into public.branches (code, name, address) values
  ('dhanmondi', 'Dhanmondi', 'Road 27, Dhanmondi, Dhaka'),
  ('banani',    'Banani',    'Road 11, Banani, Dhaka'),
  ('gulshan',   'Gulshan',   'Gulshan Avenue, Dhaka'),
  ('uttara',    'Uttara',    'Sector 7, Uttara, Dhaka'),
  ('mirpur',    'Mirpur',    'Mirpur 10, Dhaka')
on conflict (code) do nothing;

insert into public.plans (code, name, billing_period, duration_days, base_price, vat_percentage, is_popular) values
  ('basic',    'Basic',    'monthly', 30, 2000.00, 5.00, false),
  ('standard', 'Standard', 'monthly', 30, 3500.00, 5.00, true),
  ('premium',  'Premium',  'monthly', 30, 5000.00, 5.00, false)
on conflict (code) do nothing;

insert into public.plan_features (plan_id, feature_name)
select p.id, f.feature
from public.plans p
join (values
  ('basic',    'Gym Access'),
  ('basic',    'Locker Access'),
  ('basic',    'Group Classes'),
  ('standard', 'Gym Access'),
  ('standard', 'Locker Access'),
  ('standard', 'Group Classes'),
  ('standard', 'Cardio Zone'),
  ('standard', '1 Trainer Session'),
  ('premium',  'Full Gym Access'),
  ('premium',  'Personal Trainer'),
  ('premium',  'Nutrition Guidance'),
  ('premium',  'All Classes'),
  ('premium',  'Premium Locker')
) as f(code, feature) on f.code = p.code
on conflict (plan_id, feature_name) do nothing;

-- =============================================================================
-- DONE. To create your first admin:
--   Supabase Dashboard → Authentication → Users → "Add user" (email + password),
--   then sign in through the app's Login page. The trigger above auto-creates
--   the matching public.users profile row.
-- =============================================================================
