-- =============================================================================
-- 002_live_sync.sql — align the LIVE Supabase database with database/schema.sql
-- Generated from a read-only column audit (276 probes, 1 Oct 2026) that found:
--   * admission_submissions.rejection_reason  → column missing
--   * app_settings                            → table missing entirely
--   * progress_logs                           → table missing entirely
--   * anon insert policy on admission_submissions → missing (public form broken)
--
-- Idempotent: safe to run more than once. Run in the Supabase SQL Editor.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Missing column (breaks rejecting an application)
-- -----------------------------------------------------------------------------
alter table public.admission_submissions
  add column if not exists rejection_reason text;

-- -----------------------------------------------------------------------------
-- 2. Missing tables (breaks branding saves and AI progress logging)
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.app_settings (
  key        text primary key,
  value      jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.progress_logs (
  id         bigint generated by default as identity primary key,
  member_id  bigint references public.members(id) on delete set null,
  data       jsonb not null,
  created_at timestamptz default now()
);

create or replace trigger trg_app_settings_updated_at
  before update on public.app_settings
  for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- 3. RLS + staff access for the new tables
-- -----------------------------------------------------------------------------
alter table public.app_settings enable row level security;
alter table public.progress_logs enable row level security;

grant all on public.app_settings to authenticated, anon;
grant all on public.progress_logs to authenticated, anon;

drop policy if exists "authenticated all on app_settings" on public.app_settings;
create policy "authenticated all on app_settings"
  on public.app_settings for all to authenticated using (true) with check (true);

drop policy if exists "authenticated all on progress_logs" on public.progress_logs;
create policy "authenticated all on progress_logs"
  on public.progress_logs for all to authenticated using (true) with check (true);

-- -----------------------------------------------------------------------------
-- 4. Public admission form submit path (anon INSERT) — currently broken
-- -----------------------------------------------------------------------------
drop policy if exists "anon insert admissions" on public.admission_submissions;
create policy "anon insert admissions"
  on public.admission_submissions
  for insert to anon
  with check (true);

-- -----------------------------------------------------------------------------
-- 5. Staff read/update on submissions (approve & reject flow)
-- -----------------------------------------------------------------------------
drop policy if exists "authenticated all on admission_submissions" on public.admission_submissions;
create policy "authenticated all on admission_submissions"
  on public.admission_submissions
  for all to authenticated
  using (true) with check (true);

-- -----------------------------------------------------------------------------
-- 6. Default branding seed (no-op if already saved)
-- -----------------------------------------------------------------------------
insert into public.app_settings (key, value)
values ('branding', jsonb_build_object(
  'gymName', 'FitLife',
  'tagline', 'ENTERPRISE GYM',
  'logoUrl', '',
  'logoIcon', 'Flame',
  'heroTagline', 'TRAIN HARD. LIVE STRONG.',
  'heroSub', 'YOUR FITNESS. YOUR JOURNEY.',
  'phone', '+880 1711-223344',
  'email', 'contact@fitlife.com',
  'address', 'Plot 42, Gulshan Avenue, Dhaka, Bangladesh'
))
on conflict (key) do nothing;
