"""Audit: compare every column of database/schema.sql against the live Supabase DB.

One read-only REST probe per column (PostgREST validates columns even when RLS
returns zero rows), then generate an idempotent fix migration.
"""
import concurrent.futures as cf
import json
import re
import urllib.request
import urllib.error

# --- config -----------------------------------------------------------------
env = {}
for line in open('.env', encoding='utf8'):
    line = line.strip()
    if line and not line.startswith('#') and '=' in line:
        k, v = line.split('=', 1)
        env[k] = v.strip().strip('"').strip("'")
URL, KEY = env['VITE_SUPABASE_URL'], env['VITE_SUPABASE_PUBLISHABLE_KEY']

# --- parse repo schema ------------------------------------------------------
sql = open('database/schema.sql', encoding='utf8').read()
tables = {}
for m in re.finditer(r'create table (?:if not exists )?(?:public\.)?(\w+)\s*\((.*?)\n\);', sql, re.S | re.I):
    name, body = m.group(1), m.group(2)
    cols = {}
    for raw in body.splitlines():
        line = raw.split('-- ')[0].strip().rstrip(',')
        if not line:
            continue
        tok = line.split()[0].lower()
        if tok in ('primary', 'foreign', 'unique', 'check', 'constraint'):
            continue
        cm = re.match(r'([a-z_][a-z0-9_]*)\s+(.*\S)', line, re.I | re.S)
        if cm:
            cols[cm.group(1)] = ' '.join(cm.group(2).split())
    tables[name] = cols

def probe(table, col):
    req = urllib.request.Request(
        f"{URL}/rest/v1/{table}?select={col}&limit=1",
        headers={'apikey': KEY, 'Authorization': f'Bearer {KEY}'})
    try:
        urllib.request.urlopen(req, timeout=15)
        return table, col, 'ok'
    except urllib.error.HTTPError as e:
        body = e.read().decode('utf8', 'replace')
        if 'does not exist' in body and 'column' in body:
            return table, col, 'missing_col'
        if 'does not exist' in body and ('relation' in body or 'schema cache' in body):
            return table, col, 'missing_table'
        return table, col, f'http{e.code}:{body[:90]}'
    except Exception as e:
        return table, col, f'err:{e}'

jobs = [(t, c) for t, cols in tables.items() for c in cols]
print(f'probing {len(jobs)} columns across {len(tables)} tables...')

results, missing_cols, missing_tables, odd = [], {}, set(), []
with cf.ThreadPoolExecutor(max_workers=12) as ex:
    for r in ex.map(lambda a: probe(*a), jobs):
        results.append(r)
        t, c, s = r
        if s == 'missing_col':
            missing_cols.setdefault(t, []).append(c)
        elif s == 'missing_table':
            missing_tables.add(t)
        elif s != 'ok':
            odd.append(r)

# --- report -----------------------------------------------------------------
print(f"\n== RESULT: {sum(1 for r in results if r[2] == 'ok')}/{len(jobs)} columns OK")
if missing_tables:
    print('tables missing entirely:', sorted(missing_tables))
for t, cs in sorted(missing_cols.items()):
    print(f'  {t}: missing -> {cs}')
for r in odd:
    print('  unusual:', r)

# --- generate fix migration -------------------------------------------------
out = ["-- Auto-generated by scratch/audit_schema.py — aligns the LIVE database",
       "-- with database/schema.sql (columns found missing by read-only probes).",
       "-- Idempotent: safe to run more than once. Run in the Supabase SQL Editor.",
       ""]
for t, cs in sorted(missing_cols.items()):
    if t in missing_tables:
        continue
    out.append(f'-- {t}')
    for c in cs:
        out.append(f'alter table public.{t} add column if not exists {c} {tables[t][c]};')
    out.append('')
if missing_tables:
    out.append('-- WARNING: whole tables missing — restore them from database/schema.sql manually:')
    for t in sorted(missing_tables):
        out.append(f'--   {t}')
    out.append('')
out += [
    '-- Restore the public admission form submit path (see audit of Oct 1):',
    'drop policy if exists "anon insert admissions" on public.admission_submissions;',
    'create policy "anon insert admissions"',
    '  on public.admission_submissions',
    '  for insert to anon',
    '  with check (true);',
    '',
    '-- Make sure authenticated staff can read/update submissions (approve/reject):',
    'drop policy if exists "authenticated all on admission_submissions" on public.admission_submissions;',
    'create policy "authenticated all on admission_submissions"',
    '  on public.admission_submissions',
    '  for all to authenticated',
    '  using (true) with check (true);',
]
open('database/migrations/002_live_sync.sql', 'w', encoding='utf8').write('\n'.join(out) + '\n')
print('\nwrote database/migrations/002_live_sync.sql')
